### PR TITLE
UINV-24 Search and select POL plugin

### PR DESCRIPTION
**Pull request by NikitaSedyx**
https://issues.folio.org/browse/UINV-24

### CODE REVIEW

**Comment by NikitaSedyx** [comment]
hi @JohnC-80 @mkuklis 
could you please take a look at this one? I've used Component prototype methods (from module repo) to avoid copy-paste in plugin, what do you think about this approach?

**Comment by NikitaSedyx** [comment]
hi @JohnC-80 @mkuklis 
could you please take a look at this one? I've used Component prototype methods (from module repo) to avoid copy-paste in plugin, what do you think about this approach?

**Comment by NikitaSedyx** [comment]
this request requires changes from https://github.com/folio-org/ui-orders/pull/461 that's why tests are failed

**Comment by mkuklis** [comment]
@NikitaSedyx this looks like an interesting approach (it's nice that you got it working via prototype chain). I personally feel like this is a bit hacky (:)). Perhaps another approach here could be to extract the methods (and props including manifest) from `OrderLinesList` into a HOC. Then use that HOC in both `OrderLinesList` and `FindPOLineModal`.

**Comment by NikitaSedyx** [comment]
@mkuklis hm, let me think about HoC, sounds interesting

**Comment by NikitaSedyx** [comment]
it was decided to keep prototype usage and not do HoC: HoC doesn't simplify solution and doesn't make it smaller, plus a lot of methods are used in render

**Pull request merged**
